### ISSUE TITLE
How to print in a usb printer in Windows?

### ISSUE THREAD

**Issue by A1000carZ** [mjafartp/flutter_esc_pos_utils#1]
Hey i'm looking for this packages and I was wondering how I can print in a flutter windows app via usb? thanks.

**Comment by mjafartp** [comment]
we will release the USB this ver on Monday.

**Comment by A1000carZ** [comment]
Thanks!

**Comment by shakirpa** [comment]
> 
> 
> Thanks!

Hello, Is it done ? Could you please share the sample code for printing ?
Also does this package supports web app ?

**Comment by Lyazz** [comment]
Is the USB compatibility available ?

**Comment by techttiru** [comment]
> we will release the USB this ver in this Monday.

@mjafartp Hi, does this package enhanced to have the capability of connecting USB interface pos printer from flutter web application? Thanks!
