### ISSUE TITLE
support-bluetooth

### ISSUE THREAD

**Issue by jobypthomas** [mjafartp/flutter_esc_pos_utils#6]
Hello @mjafartp!
Any plan to add support/maintenance of package esc_pos_bluetooth? 

Joby

**Comment by mjafartp** [comment]
Yes,
we planing Bluetooth, USB and Network/Wifi

**Comment by jobypthomas** [comment]
@mjafartp Any timeline for the release?

**Comment by mjafartp** [comment]
End of this Month

**Comment by jobypthomas** [comment]
@mjafartp, Thank you
